Origin/phonebook
aeecleclair/Hyperion pull request #135
Opened 2023-02-26 16:49 UTC by maximeroucher

### Description

Please explain the changes you made here.

### Checklist

- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the documentation, if necessary

2023-07-30 21:06 UTC, armanddidierjean requested changes

2023-07-30 21:06 UTC, armanddidierjean commented on app/endpoints/phonebook.py
> +    requesting_user=Depends(is_user_a_member_of(GroupType.CAA)),
Shouldn't we pass the `Member` content as a Body instead of Query strings ?

2023-07-30 21:06 UTC, armanddidierjean commented on requirements.txt
Remove unneeded changes

2023-07-30 21:06 UTC, armanddidierjean commented
This PR needs to be rebased on main branch

2024-02-23 09:29 UTC, closed without merging

2024-02-23 09:30 UTC, guillaumetavernier commented
Updated PR on #342