Advert module
aeecleclair/Hyperion pull request #138
Opened 2023-02-26 16:50 UTC by maximeroucher

### Description

Please explain the changes you made here.

### Checklist

- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the documentation, if necessary

2023-08-17 18:20 UTC, armanddidierjean requested changes

2023-08-17 18:20 UTC, armanddidierjean commented on tests/test_advert.py
> +    # await add_object_to_db(group_advertiser)
Is this useful?

2023-08-22 11:53 UTC, Shaihh approved these changes

2023-08-22 11:53 UTC, Shaihh commented on app/endpoints/advert.py
> +    for advertiser in existing_advertisers:
Could not this be in cruds with a simple query like `select(models_advert.Advertiser).where(models_advert.Advertiser.group_manager_id.in_(user_groups))` ?

2023-08-30 23:09 UTC, Petitoto approved these changes

2023-08-30 23:14 UTC, merged