Tombola packticket
aeecleclair/Hyperion pull request #174
Opened 2023-04-26 08:19 UTC by landacus

### Description
- Rename TypeTicket --> PackTicket
- Manage authorization
- Update delete raffle : delete tickets, lots, packtickets and raffle linked
- Issue : cash management = admin ?

### Checklist

- [ ] Created tests which fail without the change (if possible)
- [x ] All tests passing
- [ ] Extended the documentation, if necessary

2023-04-27 21:11 UTC, Jake-Ransom requested changes
Great work everything seems fine to me !! I just requested some changes on typos or other details.

2023-04-27 21:11 UTC, Jake-Ransom commented on app/endpoints/raffle.py
> +async def locked_raffle(
```suggestion
async def lock_raffle(
```

2023-04-27 21:11 UTC, Jake-Ransom commented on app/endpoints/raffle.py
> +    "/tombola/raffles/{raffle_id}/locked",
```suggestion
    "/tombola/raffles/{raffle_id}/lock",
```

2023-04-27 21:11 UTC, Jake-Ransom commented on app/endpoints/raffle.py
> +    await cruds_raffle.locked_raffle(db=db, raffle_id=raffle_id)
Before that, you should check that the raffle is currently opened.

2023-04-27 21:11 UTC, Jake-Ransom commented on app/endpoints/raffle.py
> +    await cruds_raffle.open_raffle(db=db, raffle_id=raffle_id)
Before that, you should check that the raffle is currently in creation.

2023-04-27 21:11 UTC, Jake-Ransom commented on tests/test_raffle.py
>  soli_user: models_core.CoreUser | None = None
Please remove the soli user and the group soli from the group_types, as it is no longer used in the module.

2023-04-28 16:05 UTC, armanddidierjean requested changes

2023-04-29 14:35 UTC, Jake-Ransom commented on app/models/models_raffle.py
>      lot: Lots | None = relationship("Lots")
YES please !

2023-05-01 15:40 UTC, Jake-Ransom approved these changes

2023-05-04 21:17 UTC, armanddidierjean commented on app/cruds/cruds_raffle.py
> +) -> list[models_raffle.Raffle] | None:
With `all()` method, the crud will return an empty list instead of None
```suggestion
) -> list[models_raffle.Raffle]:
```

2023-07-11 18:51 UTC, armanddidierjean requested changes

2023-07-13 08:56 UTC, Petitoto approved these changes

2023-07-17 21:41 UTC, merged