feat: support Pydantic V2
aeecleclair/Hyperion pull request #281
Opened 2023-11-06 12:45 UTC by AtomHare

### Description

This PR adds the necessary modifications in order to support Pydantic breaking changes !

HOWEVER, do not use in production already, please test it thoroughly to verify that everything is working.

2023-11-29 14:49 UTC, armanddidierjean requested changes
Creating new loan items does not work with Titan:

 - on creation Hyperion send a 201 but Titan raise an error
 - on getting items Titan raise an error "get a string instead of float"

2024-01-14 18:56 UTC, armanddidierjean commented
Do you think you could write a migration file to change the Interval to an Int in the database @Rotheem?
<img width="720" alt="Capture d’écran 2024-01-14 à 19 55 03" src="https://github.com/aeecleclair/Hyperion/assets/95971503/d1f438a5-2182-43e8-a7a5-3bf1aa3b8476">

2024-02-22 14:19 UTC, armanddidierjean commented on app/schemas/schemas_loan.py
> +    suggested_lending_duration: int | None = Field(
This should be two equivalent syntaxes

2024-02-22 14:23 UTC, AtomHare commented on app/schemas/schemas_notification.py
>      firebase_device_token: str = Field("Firebase device token")
You're right this should be changed however it's not in the scope of this PR

2024-02-22 14:24 UTC, AtomHare commented on app/endpoints/amap.py
> +    db_product = models_amap.Product(id=str(uuid.uuid4()), **product.__dict__)
If I recall correctly  `model_dump` doesn't work here

2024-02-22 16:47 UTC, guillaumetavernier approved these changes

2024-02-23 07:29 UTC, Rotheem approved these changes

2024-02-23 09:36 UTC, armanddidierjean approved these changes
I couldn't test the PR, but the code looks good to me

2024-02-23 10:10 UTC, merged