Refactor module visibility to add visibility for new modules
aeecleclair/Hyperion pull request #359
Opened 2024-03-02 14:06 UTC by armanddidierjean

### Description

With this PR, modules visibility are stored with a column `visible: bool` in db.

This allows at startup to add default group ids for new modules, instead of only adding them during the database first initialization

2024-03-15 20:23 UTC, Petitoto approved these changes

2024-03-16 10:45 UTC, Rotheem requested changes

2024-03-16 10:45 UTC, Rotheem commented on app/core/models_core.py
> +    visible: Mapped[bool] = mapped_column(Integer, nullable=False, default=True)
This should be a boolean and not an Integer

2024-04-24 15:59 UTC, julien4215 requested changes

2024-04-24 15:59 UTC, julien4215 commented on app/core/endpoints_core.py
> +    # We need to import the module_list here, because the it is not initialized at startup
```suggestion
    # We need to import the module_list here, because it is not initialized at startup
```

2024-04-24 15:59 UTC, julien4215 commented on app/app.py
> +            if module_awareness is None:
```suggestion
            if module_awareness is not None:
```

2024-04-29 20:30 UTC, julien4215 commented
Instead of deleting the ModuleVisibility table, the migration file could add all modules in the table ModuleAwarness because all these modules already use visibily

2025-04-10 14:46 UTC, armanddidierjean commented
Completed in https://github.com/aeecleclair/Hyperion/pull/612

2025-04-10 14:46 UTC, closed without merging