Fix phonebook : kinds enum and types file
aeecleclair/Hyperion pull request #383
Opened 2024-03-20 00:54 UTC by Rotheem

### Description

Please explain the changes you made here.

### Checklist

- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the documentation, if necessary

2024-03-20 05:50 UTC, guillaumetavernier commented on migrations/versions/6-phonebook.py
> +        sa.Column(
Isn't it possible to use the enum define in type rather than hard code values twice?

2024-03-20 07:08 UTC, julien4215 requested changes

2024-03-20 07:08 UTC, julien4215 commented on tests/test_phonebook.py
> +    event_loop,
Why did you remove the `# noqa` ?

2024-03-20 07:08 UTC, julien4215 commented on tests/test_phonebook.py
> -association: models_phonebook.Association | None = None
Why did you delete these lines ?

2024-03-20 07:23 UTC, julien4215 commented on app/modules/phonebook/types_phonebook.py
> +class RoleTags(str, Enum):
We are not using this Enum as a string so I guess we don't need to inherit from str.

2024-03-20 07:23 UTC, julien4215 commented on app/modules/phonebook/types_phonebook.py
> +class Kinds(str, Enum):
Same here

2024-03-21 08:13 UTC, Rotheem commented on tests/test_phonebook.py
> -association: models_phonebook.Association | None = None
I think my extensions did weird things

2024-03-29 09:39 UTC, julien4215 approved these changes

2024-03-29 11:34 UTC, Foukki approved these changes

2024-03-29 11:34 UTC, merged