Add Documenso provider
aeecleclair/Hyperion pull request #516
Opened 2024-08-14 08:48 UTC by armanddidierjean

2024-08-15 00:46 UTC, Rotheem approved these changes

2024-11-12 20:57 UTC, maximeroucher approved these changes

2024-11-13 22:51 UTC, Rotheem commented on migrations/versions/25-hardcode-eclair-group.py
> +    conn.execute(t_group.delete().where(t_group.c.id == old_eclair_id))
This will fail as eclair's group is used in seller, loan...

2024-11-13 22:52 UTC, Rotheem requested changes

2024-11-13 22:52 UTC, Rotheem commented on migrations/versions/25-hardcode-eclair-group.py
> +    conn.execute(t_group.delete().where(t_group.c.id == old_eclair_id))
This will fail as eclair's group is used in seller, loan,...

2024-11-16 09:56 UTC, Rotheem approved these changes

2024-11-16 09:56 UTC, merged