Remove deprecated base image and use uv
aeecleclair/Hyperion pull request #580
Opened 2024-09-25 08:32 UTC by julien4215

2024-09-25 22:32 UTC, Rotheem commented on start.sh
> +exec fastapi run app/main.py "$@"
Use environment variables instead of command arguments
```suggestion
exec fastapi run app/main.py --workers ${NB_WORKERS:1}
```

2024-09-25 22:33 UTC, Rotheem commented on docker-compose.yaml
> +    command: ["--port", "80"]
There is no need to change port through the docker-compose
```suggestion
```

2024-09-26 00:53 UTC, Rotheem approved these changes

2024-09-26 10:51 UTC, armanddidierjean requested changes

2024-09-27 10:25 UTC, Foukki approved these changes

2024-09-27 10:29 UTC, merged