Transform AccountType from groups to user's attribute
aeecleclair/Hyperion pull request #612
Opened 2024-10-27 16:59 UTC by Rotheem

### Description

Please explain the changes you made here.

### Checklist

- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the documentation, if necessary

2024-11-21 10:04 UTC, armanddidierjean requested changes

2024-11-24 11:10 UTC, armanddidierjean requested changes

2024-11-24 11:10 UTC, armanddidierjean commented on tests/commons.py
> +    account_type: AccountType = AccountType.external,
I think by default we could create student users. This corresponds to the most common use case.

2024-12-02 11:45 UTC, Rotheem commented on app/utils/initialization.py
> +def get_core_data_sync(schema: str, db: Session) -> models_core.CoreData | None:
It is already the same

2024-12-02 16:10 UTC, armanddidierjean requested changes
Could you increase test coverage in `endpoints_user` and `endpoints_core`?

2024-12-03 12:52 UTC, foucblg approved these changes

2024-12-03 13:57 UTC, Rotheem commented on app/utils/initialization.py
> +def get_core_data_sync(schema: str, db: Session) -> models_core.CoreData | None:
Done

2024-12-03 14:38 UTC, Daihecyy approved these changes
Consider changing list to generator in tools.py to improve drastically performances

2024-12-03 15:08 UTC, armanddidierjean commented on app/core/groups/groups_type.py
> +    # demo = "ae4d1866-e7d9-4d7f-bee7-e0dda24d8dd8"
I believe we can delete these lines

2024-12-03 15:11 UTC, armanddidierjean commented on app/dependencies.py
> +    def is_user(
Three cases remains untested, would you mind adding a test for them?
- `excluded_account_types`
- `is_user_external`
- `included_account_types`

2024-12-03 19:16 UTC, armanddidierjean approved these changes
Really impressive and brilliant PR!

2024-12-03 21:49 UTC, merged

2024-12-03 22:15 UTC, Rotheem commented
> Consider changing list to generator in tools.py to improve drastically performances

Do not consider this comment it's BS