Jinja templating
aeecleclair/Hyperion pull request #629
Opened 2024-12-04 23:46 UTC by Daihecyy

### Description
Changed email templates to use a Jinja base template, created a python helper function to test the templates and improved phrasing

2024-12-05 09:25 UTC, armanddidierjean requested changes

2024-12-05 11:58 UTC, Daihecyy commented on assets/templates/template_tester.py
No real interest as the main purpose is to check how it looks, Jinja will always compile as it can already be considered HTML

2024-12-06 16:44 UTC, Daihecyy commented on assets/templates/template_tester.py
Pls resolve

2024-12-15 17:18 UTC, Marc-Andrieu approved these changes
Really nice refactoring!

I could argue on some rewritings of the English translations which you made while you were at it (why not having a separate PR for that? that's not the point of this PR).
But I won't bother you on it for now (on this PR at least!), bc I'd like it to be merged.

2025-01-02 19:18 UTC, armanddidierjean approved these changes

2025-01-03 13:04 UTC, merged