data-base-migration
aeecleclair/Hyperion pull request #7
Opened 2022-04-06 14:30 UTC by Nathanael-lscx

### Description
+ Rebuilding structure : adapt database and documentation to eachother
+ Adding async and migration
+ First requests working

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the documentatioe, if necessary

2022-04-07 07:45 UTC, Victor-Angot approved these changes
Don't forget to add documentation especially on the alambic part

2022-04-07 08:02 UTC, Jhobahtes requested changes

2022-04-07 08:02 UTC, Jhobahtes commented on app/main.py
> +#         await conn.run_sync(Base.metadata.create_all)
Could you modify this part?

2022-04-09 20:26 UTC, Jhobahtes commented
TODO:
 * [ ] Check dependencies (greenlet probably missing)

2022-04-10 10:16 UTC, Jhobahtes commented on app/endpoints/groups.py
> +    """Return all groups from database as a list of dictionaries"""
The returned object is more a list of `schemas_core.CoreGroupSimple` than a dictionary.

```suggestion
    """Return all groups"""
```

2022-04-10 10:16 UTC, Jhobahtes commented on tests/test_users.py
> +client = TestClient(app)  # Run the tests
This line does not really run the tests. The idea is more to create a test client that is able to execute requests

2022-04-10 13:35 UTC, Jake-Ransom commented
> TODO:

2022-04-10 13:36 UTC, Jake-Ransom commented
la glissade

2022-04-10 16:44 UTC, Jhobahtes approved these changes

2022-04-11 12:01 UTC, Victor-Angot approved these changes

2022-04-11 12:01 UTC, merged